//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SMTrader.rc
//
#define ID_APPLY                        3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_VROBO_FORM                  102
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_SMTraderTYPE                130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_SYMBOL_SELECTOR             308
#define IDD_HDF_CTRL                    310
#define IDD_SYM_CAT1                    311
#define IDD_ORDER_LEFT_HD               312
#define IDR_PRDT_256                    313
#define IDD_SYS_AUTO_CONNECT            313
#define IDD_SYM_CAT2                    314
#define IDB_SORT_25                     314
#define IDD_SYM_CAT3                    315
#define IDB_PROPERTIES_HC1              315
#define IDD_ORDER_CENTER_HD             316
#define IDB_MENU_IMAGES_25              316
#define IDD_SYM_CAT4                    317
#define IDB_FILE_VIEW_25                317
#define IDD_SYM_CAT5                    318
#define IDB_FILE_VIEW1                  318
#define IDD_ORDER_RIGHT_HD              319
#define IDB_EXPLORER_25                 319
#define IDD_SYM_CAT6                    320
#define IDB_CLASS_VIEW_25               320
#define IDD_ORDER_RIGHT_CONFIG_HD       321
#define IDB_CLASS_VIEW1                 321
#define IDD_CHART                       322
#define IDD_ORDER_WND_HD                323
#define IDB_BITMAP_OUT                  323
#define IDB_BITMAP_CANCEL               324
#define IDD_ADD_SIG_CONNECT             324
#define IDD_SYMBOL_SELECTER_HD          325
#define IDD_FUND_SUBACCOUNTPAGE         326
#define IDD_ORDER_WND                   327
#define IDD_ORDER_LEFT                  328
#define IDD_ORDER_CENTER                329
#define IDD_ORDER_RIGHT                 330
#define IDD_ORDER_SETTLE                331
#define IDD_ORDER_CONFIG                332
#define IDD_SYMBOL_FAVORITE             333
#define IDD_DIALOG_CHART                334
#define IDD_FUT_PAGE                    335
#define IDD_FUND_ACCOUNTPAGE            336
#define IDD_ADD_SIG_DEF                 337
#define IDD_MINI_JANGO                  338
#define IDD_AUTOSIG_CONFIG              339
#define IDD_BUSY_DLG                    340
#define IDD_ORDER_TOTAL                 341
#define IDB_CALC_ANIM2                  342
#define IDD_REAL_TICK                   344
#define IDD_DIALOG_EMBED                346
#define IDD_SYSTEM_ORDER_CONFIG         347
#define IDD_CENTER_CONFIG               348
#define IDD_REALTIMETRACK_DIALOG        349
#define IDD_ZOOMSCROLLTRACK2_DIALOG     350
#define IDD_INDEX_PROPERTY              351
#define IDD_ORDERGRID_CONFIG            352
#define IDD_SYS_ORDER                   353
#define IDD_CHART_PROPERTY              354
#define IDD_ASSET_CONTAINER             355
#define IDD_SYS_LOG                     356
#define IDD_REGISTER_USER               357
#define IDD_ASSET                       358
#define IDD_LOGIN                       359
#define IDD_ORDER_AVAILABLE             360
#define IDD_SYS_SET_MONTH               361
#define IDD_MESSAGE_BOARD               362
#define IDD_ORDER_RIGHT_CANCEL_HD       363
#define IDD_OPT_PAGE                    364
#define IDD_ACCOUNT_ASSET               365
#define IDD_ORDER_PANEL                 366
#define IDD_SUBACNT                     367
#define IDD_FUND_EDITOR                 368
#define IDD_PORT_COR                    370
#define IDD_FUND_DESIGNER               371
#define IDB_BITMAP_PORT                 373
#define IDB_BITMAP_GLASS                374
#define IDD_FUND_NAME                   375
#define IDB_BITMAP1                     375
#define IDB_BITMAP_S2                   375
#define IDD_ORDER_CENTER_FUND           376
#define IDD_MINI_JANGO_FUND             377
#define IDD_ACCOUNT_PWD                 378
#define IDD_SYS_PROP                    380
#define IDD_CHART_CONTAINER             384
#define IDD_DIALOG_CHART1               385
#define IDD_TIME_TOOLBAR                386
#define IDD_SYSTEM_PROPERTY             388
#define IDD_PROGRESS                    391
#define IDI_SEARCH                      393
#define IDD_MAIN_TOOLBAR                394
#define IDB_BITMAP_DOWN                 396
#define IDB_BITMAP_UP                   397
#define IDD_STRATEGE_TOOLS              398
#define IDB_BITMAP_SET                  403
#define IDD_DATA_COL                    404
#define IDB_BITMAP_DOWN_TRI             406
#define IDB_BITMAP_UP_TRI               407
#define IDD_SYSTEM_USD                  410
#define IDD_ACNT_FUND_SELECTOR          412
#define IDI_SEARCH16                    414
#define ID_CHART_HSCRL                  415
#define ID_CHART_EDIT_COUNT             416
#define IDI_SEARCH4                     416
#define ID_CHART_BTN_ZOOMIN             417
#define IDI_LEFT                        417
#define ID_CHART_BTN_ZOOMOUT            418
#define IDI_RIGHT                       418
#define ID_CHART_BTN_FULLSCRN           419
#define IDI_MINUS                       419
#define ID_CHART_BTN_DEL                420
#define IDI_PLUS                        420
#define IDI_SET                         421
#define IDB_BITMAP_SET2                 422
#define IDB_BITMAP_TOOL                 423
#define IDB_BITMAP_TOOL2                424
#define IDI_DOWN                        425
#define IDI_UP                          426
#define IDD_LOGIN_MAIN                  427
#define IDI_CLASS_VIEW1                 427
#define ID_SPLIT1                       500
#define ID_SPLIT2                       501
#define ID_SPLIT3                       502
#define ID_SPLIT4                       503
#define ID_SPLIT5                       504
#define ID_SPLIT6                       505
#define ID_SPLIT7                       506
#define ID_SPLIT8                       507
#define ID_SPLIT9                       508
#define ID_SPLIT10                      509
#define ID_SPLIT11                      510
#define ID_SPLIT12                      511
#define ID_SPLIT13                      512
#define ID_SPLIT14                      513
#define ID_SPLIT15                      514
#define ID_SPLIT16                      515
#define ID_SPLIT17                      516
#define ID_SPLIT18                      517
#define ID_SPLIT19                      518
#define ID_SPLIT20                      519
#define ID_SPLIT21                      520
#define ID_SPLIT22                      521
#define ID_SPLIT23                      522
#define ID_SPLIT24                      523
#define ID_SPLIT25                      524
#define ID_SPLIT26                      525
#define ID_SPLIT27                      526
#define ID_SPLIT28                      527
#define ID_SPLIT29                      528
#define ID_SPLIT30                      529
#define ID_SPLIT31                      530
#define ID_SPLIT32                      531
#define ID_SPLIT33                      532
#define ID_SPLIT34                      533
#define ID_SPLIT35                      534
#define ID_SPLIT36                      535
#define ID_SPLIT37                      536
#define ID_SPLIT38                      537
#define ID_SPLIT39                      538
#define ID_SPLIT40                      539
#define ID_SPLIT41                      540
#define ID_SPLIT42                      541
#define ID_SPLIT43                      542
#define ID_SPLIT44                      543
#define ID_SPLIT45                      544
#define ID_SPLIT46                      545
#define ID_SPLIT47                      546
#define ID_SPLIT48                      547
#define ID_SPLIT49                      548
#define ID_SPLIT50                      549
#define ID_SPLIT51                      550
#define ID_SPLIT52                      551
#define ID_SPLIT53                      552
#define ID_SPLIT54                      553
#define ID_SPLIT55                      554
#define ID_SPLIT56                      555
#define ID_SPLIT57                      556
#define ID_SPLIT58                      557
#define ID_SPLIT59                      558
#define ID_SPLIT60                      559
#define ID_SPLIT61                      560
#define ID_SPLIT62                      561
#define ID_SPLIT63                      562
#define ID_SPLIT64                      563
#define ID_SPLIT65                      564
#define ID_SPLIT66                      565
#define ID_SPLIT67                      566
#define ID_SPLIT68                      567
#define ID_SPLIT69                      568
#define ID_SPLIT70                      569
#define ID_SPLIT71                      570
#define ID_SPLIT72                      571
#define ID_SPLIT73                      572
#define ID_SPLIT74                      573
#define ID_SPLIT75                      574
#define ID_SPLIT76                      575
#define ID_SPLIT77                      576
#define ID_SPLIT78                      577
#define ID_SPLIT79                      578
#define ID_SPLIT80                      579
#define ID_SPLIT81                      580
#define ID_SPLIT82                      581
#define ID_SPLIT83                      582
#define ID_SPLIT84                      583
#define ID_SPLIT85                      584
#define ID_SPLIT86                      585
#define ID_SPLIT87                      586
#define ID_SPLIT88                      587
#define ID_SPLIT89                      588
#define ID_SPLIT90                      589
#define ID_SPLIT91                      590
#define ID_SPLIT92                      591
#define ID_SPLIT93                      592
#define ID_SPLIT94                      593
#define ID_SPLIT95                      594
#define ID_SPLIT96                      595
#define ID_SPLIT97                      596
#define ID_SPLIT98                      597
#define ID_SPLIT99                      598
#define ID_SPLIT100                     599
#define ID_SPLIT101                     600
#define ID_SPLIT102                     601
#define ID_SPLIT103                     602
#define ID_SPLIT104                     603
#define ID_SPLIT105                     604
#define ID_SPLIT106                     605
#define ID_SPLIT107                     606
#define ID_SPLIT108                     607
#define ID_SPLIT109                     608
#define ID_SPLIT110                     609
#define ID_SPLIT111                     610
#define ID_SPLIT112                     611
#define ID_SPLIT113                     612
#define ID_SPLIT114                     613
#define ID_SPLIT115                     614
#define ID_SPLIT116                     615
#define ID_SPLIT117                     616
#define ID_SPLIT118                     617
#define ID_SPLIT119                     618
#define ID_SPLIT120                     619
#define IDC_ChartViewer                 1000
#define IDC_ASSET                       1000
#define IDC_STATIC_ASSET                1000
#define IDC_STATIC_ID                   1000
#define IDC_TAB_CATEGORY                1001
#define IDC_SYMBOL_OPTION               1001
#define IDC_STATIC_PWD                  1001
#define ID_OK                           1002
#define IDC_RADIO_BALANCE               1002
#define IDC_STATIC_CERT                 1002
#define IDC_RADIO_CURRENT               1003
#define IDC_UpdatePeriod                1004
#define IDC_RADIO_EXPECT                1004
#define IDC_BUTTON1                     1004
#define IDC_BTN_CAN                     1004
#define IDC_PointerPB                   1005
#define IDC_PROFIT_LOSS                 1005
#define IDC_STATIC_POSITION             1005
#define IDC_ZoomInPB                    1006
#define IDC_COMBO_PRODUCT               1006
#define IDC_EDIT_ACNT_PWD               1006
#define IDC_STATIC_CHART                1006
#define IDC_CHECK1                      1006
#define IDC_ZoomOutPB                   1007
#define IDC_STATIC_LEFT                 1007
#define IDC_COMBO_OPTION                1007
#define IDC_CHECK2                      1007
#define IDC_BTN_MONTH                   1008
#define IDC_BTN_ACCOUNT                 1008
#define IDC_BTN_SHOW_LEFT               1008
#define IDC_STATIC_CENTER               1008
#define IDC_BTN_CANCEL_LAST             1008
#define IDC_SYMBOL_FUTURE               1008
#define IDC_BTN_ACNT_ORDER              1008
#define IDC_BTN_ACNT_IN                 1008
#define IDC_BTN_FUND_NEW                1008
#define IDC_BTN_START                   1008
#define IDC_BTN_COMMIT                  1008
#define IDC_BUTTON2                     1008
#define IDC_CHECK_SAVE                  1009
#define IDC_BTN_WEEK                    1009
#define IDC_BTN_SYMBOL                  1009
#define IDC_FreezePB                    1009
#define IDC_CHECK_SHOW_PLCONFIGWND      1009
#define IDC_BTN_SHOWRIGHT               1009
#define IDC_STATIC_RIGHT                1009
#define IDC_CHECK_SHOW_CANCEL_ORDER     1009
#define IDC_CK_FROMRECENT               1009
#define IDC_CHECK_THOUSAND              1009
#define IDC_BTN_MOD                     1009
#define IDC_BTN_ACNT_IN_ALL             1009
#define IDC_BTN_FUND_SETTINGS           1009
#define IDC_BTN_DAY                     1010
#define IDC_CHECK_LOSSCUT               1010
#define IDC_AlphaValue                  1010
#define IDC_CHECK_SHOW_ORDERCOL         1010
#define IDC_BTN_DELWND                  1010
#define IDC_CHECK_SHOW_REAL_ACCOUNT_ONLY 1010
#define IDC_SPACEBAR_ORDER              1010
#define IDC_STATIC_ACCEPTED             1010
#define IDC_CHECK_SUBACNT               1010
#define IDC_BTN_CREATE                  1010
#define IDC_BTN_ACNT_OUT                1010
#define IDC_BTN_FUND_MODIFY             1010
#define IDC_CHECK_SHOW_PWD              1010
#define IDC_BUTTON4                     1010
#define IDC_BTN_ORDER_CONFIG            1010
#define IDC_EDIT_ID                     1011
#define IDC_BTN_MIN                     1011
#define IDC_CHECK_TS                    1011
#define IDC_BetaValue                   1011
#define IDC_EDIT_TICK_COUNT             1011
#define IDC_BTN_ADDWND                  1011
#define IDC_EDIT_ACCOUNT_NAME           1011
#define IDC_EDIT_CANCEL                 1011
#define IDC_STATIC_REMAIN_LIST          1011
#define IDC_EDIT_AMT                    1011
#define IDC_EDIT_SUBACNT_CODE           1011
#define IDC_BTN_ACNT_OUT_ALL            1011
#define IDC_BTN_FUND_DELETE             1011
#define IDC_STATIC_TOTAL_SIGNAL         1011
#define IDC_EDIT_PWD                    1012
#define IDC_BTN_TICK                    1012
#define IDC_EDIT_ENT_MAX                1012
#define IDC_GammaValue                  1012
#define IDC_EDIT_CELL_HEIGHT            1012
#define IDC_STATIC_REMAIN_TOTAL         1012
#define IDC_EDIT_SUB_ACNT_NAME          1012
#define IDC_EDIT_SEUNSU                 1012
#define IDC_EDIT_CUT_LOSS               1012
#define IDC_STATIC_SIGNAL_CONNECTION    1012
#define IDC_EDIT_CERT                   1013
#define IDC_CHECK_PROFIT_TARGET         1013
#define IDC_BTN_DOWN                    1013
#define IDC_RunPB                       1013
#define IDC_BTN_SAVE                    1013
#define IDC_SPIN_CUT_PROFIT             1013
#define IDC_STATIC_SIGNAL_DEFINITION    1013
#define IDC_SPIN_ORDER_AMT              1014
#define IDC_BTN_UP                      1014
#define IDC_BTN_CLOSE                   1014
#define IDC_SPIN_CUT_LOSS               1014
#define IDC_BTN_ADD_CONNECT             1014
#define IDC_COMBO_PRODUCT5              1015
#define IDC_BTN_DEL                     1015
#define IDC_BUSY_PIC                    1015
#define IDC_BTN_ADD_SIGNAL              1015
#define IDC_COMBO_ACCOUNT5              1016
#define IDC_BUSY_TEXT                   1016
#define IDC_COMBO_ACNT                  1016
#define IDC_BTN_DEL_CONNECT             1016
#define IDC_BTN_EXTRA_VAR               1017
#define IDC_BTN_EDIT_FUND               1017
#define IDC_BTN_CANCEL_SELECTED         1017
#define IDC_EDIT_ORDER_CELL_WIDTH       1017
#define IDC_FUND_ORDER                  1017
#define IDC_INDEX_PROPERTY              1017
#define IDC_BTN_END                     1017
#define IDC_BTN_SEARCH                  1017
#define IDC_BTN_DEL_SIGNAL              1017
#define IDC_RADIO_TICKLEFT              1018
#define IDC_CANCEL_LAST_ORDER           1018
#define IDC_SPIN_ORDER_CELL_HEIGHT      1018
#define IDC_BTN_INSERT                  1018
#define IDC_RADIO_ENTIRE                1018
#define IDC_COMBO_SIGNAL                1018
#define IDC_BTN_ORDER_AMT1              1019
#define IDC_PROP_CHART                  1019
#define IDC_RADIO_ACNT                  1019
#define IDC_EDIT_SIGNAL                 1019
#define IDC_BTN_APPLY                   1020
#define IDC_BTN_ORDER_AMT2              1020
#define IDC_RADIO_FUND                  1020
#define IDC_EDIT_USER_ID                1021
#define IDC_BTN_ORDER_AMT3              1021
#define IDC_SPIN_SEUNGSU                1021
#define IDC_EDIT_USER_PWD               1022
#define IDC_BTN_ORDER_AMT4              1022
#define IDC_BTN_REGISTER_USER           1023
#define IDC_BTN_ORDER_AMT5              1023
#define IDC_EDIT_SYMBOL                 1023
#define IDC_HScrollBar                  1024
#define IDC_BTN_LOGIN                   1024
#define IDC_BTN_ORDER_AMT6              1024
#define IDC_EDIT_STRATEGY               1024
#define IDC_RADIO_TICKRIGHT             1025
#define IDC_CANCEL_SELECTED             1025
#define IDC_EDIT_DESC                   1025
#define IDC_STARTDATE                   1026
#define IDC_EDIT_ORDER_TYPE_SLIP        1026
#define IDC_BTN_FIND_SYMBOL             1026
#define IDC_ENDDATE                     1027
#define IDC_SPIN_ORDER_TYPE_SLIP        1027
#define IDC_EDIT_SEUNGSU                1027
#define IDC_BTN_RIGHT_EXTEND            1028
#define IDC_COMBO_TYPE                  1028
#define IDC_CK_LIQ_ALL                  1029
#define IDC_CHECK_SHOW_STOPCOL          1029
#define IDC_EDIT_PS_STOP                1029
#define IDC_FORMAT_THOUSAND             1029
#define IDC_COMBO_PRICE                 1029
#define IDC_COMBO_ACCOUNT_HD            1030
#define IDC_SPIN_ORDER_CELL_WIDTH       1030
#define IDC_EDIT_TICK                   1030
#define IDC_EDIT_TS_DEFAULT_LOSS        1031
#define IDC_COMBO_PRODUCT_HD            1031
#define IDC_BTN_FV1                     1031
#define IDC_SPIN_TICK                   1031
#define IDC_EDIT_TS_PROFIT              1032
#define IDC_STATIC_MSG                  1032
#define IDC_BTN_FV2                     1032
#define IDC_COMBO_PRICE_TYPE            1032
#define IDC_EDIT_TS_TRAIL               1033
#define IDC_CK_FIXED_CENTER             1033
#define IDC_BTN_FV3                     1033
#define IDC_BTN_SYS_ORDER               1033
#define IDC_EDIT_TS_STOP                1034
#define IDC_BTN_FV4                     1034
#define IDC_RADIO_ATPRICE               1034
#define IDC_BTN_FV5                     1035
#define IDC_STATIC_LOG                  1035
#define IDC_BTN_FV8                     1036
#define IDC_CHECK_CUT_PROFIT            1036
#define IDC_CHECK_FILTER_HOGA           1036
#define IDC_BTN_FV6                     1037
#define IDC_CHECK_CUT_LOSS              1037
#define IDC_COMBO_KP                    1037
#define IDC_BTN_FV7                     1038
#define IDC_EDIT_CUT_PROFIT             1038
#define IDC_COMBO_KQ                    1038
#define IDC_ORDER_GRID                  1038
#define IDC_BUTTON_SETTING              1039
#define IDC_BTN_FAVORITE                1039
#define IDC_COMBO_UD                    1039
#define IDC_BTN_LIQ_ALL                 1040
#define IDC_BTN_REMAIN                  1040
#define IDC_BTN_LIQ_SEL                 1041
#define IDC_BTN_AVAIL                   1041
#define IDC_TAB_SYMBOL                  1042
#define IDC_BTN_CANCEL_ALL              1042
#define IDC_BTN_LIQ                     1042
#define IDC_TAB_FUTOPT                  1043
#define IDC_TAB_CONFIG                  1043
#define IDC_BTN_CANCEL_SEL              1043
#define IDC_BTN_REMAIN_FUND             1043
#define IDC_STATIC_ORDER_PANEL          1044
#define IDC_STATIC_FUT_GRID             1044
#define IDC_STATIC_OPT_GRID             1045
#define IDC_CUSTOM1                     1045
#define IDC_CUSTOM_OPTION               1045
#define IDC_STATIC_PRODUCT_NAME         1046
#define IDC_COMBO_FUT_MARKET            1046
#define IDC_CUSTOM_FUTURE               1046
#define IDC_STATIC_PRODUCT_REMAIN       1047
#define IDC_STATIC_FUT                  1047
#define IDC_CUSTOM_PL                   1047
#define IDC_STATIC_ACNT_NAME            1048
#define IDC_STATIC_REAL_TICKQUOTE       1048
#define IDC_COMBO_OPT_MARKET            1048
#define IDC_CUSTOM_ASSET                1048
#define IDC_STATIC_ACCOUNT_REMAIN       1049
#define IDC_COMBO_OPT_MONTH             1049
#define IDC_CHECK_ALL                   1049
#define IDC_ONE_CLICK                   1050
#define IDC_STATIC_SYMBOL_MASTER        1050
#define IDC_BUTTON_SEARCH               1050
#define IDC_STATIC_CANCEL               1051
#define IDC_BTN_LEFT_EXTEND             1051
#define IDC_STATIC_COR                  1051
#define IDC_CHECK_ONECLICK              1052
#define IDC_STATIC_MINI_SUB             1052
#define IDC_CHECK_FIX_HOGA              1053
#define IDC_STATIC_MINI_TOP             1053
#define IDC_COMBO_ACCOUNT               1054
#define IDC_RADIO_CANCEL_LASTORDER      1054
#define IDC_RADIO_CANCEL_ORDER_BYSELPOS 1055
#define IDC_MFCBUTTON_STATE             1056
#define IDC_SPIN_PS_STOP                1056
#define IDC_COMBO_SYMBOL                1057
#define IDC_CHECK_ORDER_BYSPACE         1057
#define IDC_STATIC_ORDER                1058
#define IDC_SPIN_TS_DEFAULT_LOSS        1058
#define IDC_CHECK_USE_SHORTCUT          1058
#define IDC_STATIC_REAL_TICK            1059
#define IDC_SPIN_PS_PROFIT              1059
#define IDC_CHECK_CONFIRM_SHORTCUTORDER 1059
#define IDC_SPIN_TS                     1060
#define IDC_EDIT_STOPVAL                1060
#define IDC_RADIO_BY_MOUSE_SELECT       1061
#define IDC_SPIN_STOPVAL                1061
#define IDC_RADIO_BY_MOUSE_POS          1062
#define IDC_EDIT_ORDER_AMOUNT           1062
#define IDC_SPIN_TS_STOP                1063
#define IDC_SPIN_ORDER_AMOUNT           1063
#define IDC_CHECK_PROFIT                1064
#define IDC_CHECK_LOSS                  1065
#define IDC_EDIT_PROFIT                 1066
#define IDC_STATIC_FILL_PL              1066
#define IDC_EDIT_LOSS                   1067
#define IDC_STATIC_ORDER_TYPE           1067
#define IDC_CHECK_SHOW_COUNTCOL         1068
#define IDC_SPIN_PROFIT                 1068
#define IDC_CHECK_SHOW_TICKWND          1069
#define IDC_SPIN_LOSS                   1069
#define IDC_EDIT_CELL_WIDTH             1070
#define IDC_BUTTON_PROFIT_LOSS          1070
#define IDC_RADIO_ATMARKET              1071
#define IDC_TAB_ASSET_CONTAINER         1071
#define IDC_RADIO_STOP                  1072
#define IDC_CHECK_TRAIL_STOP            1073
#define IDC_TAB_ACCOUNT_ASSET           1073
#define IDC_RADIO_TS_ATMARKET           1074
#define IDC_STATIC_ACNT                 1075
#define IDC_RADIO_TS_STOP               1075
#define IDC_EDIT_ORDER_CELL_HEIGHT      1076
#define IDC_STATIC_STOP                 1076
#define IDC_BTN_GET_ACNT_INFO           1077
#define IDC_STATIC_REMAIN               1078
#define IDC_TAB_FD                      1078
#define IDC_STATIC_ORDER_AVBL           1079
#define IDC_TREE_FUNDLIST               1079
#define IDC_BTN_SEL_SYMBOL              1080
#define IDC_STATIC_FUND_DETAIL          1080
#define IDC_BTN_OK                      1081
#define IDC_BTN_OUT_ONE                 1082
#define IDC_BTN_CANCEL                  1082
#define IDC_BTN_OUT_ALL                 1083
#define IDC_EDIT_FUND_NAME              1083
#define IDC_STATIC_FAVORITE             1084
#define IDC_STATIC_SUM_SEUNGSU          1084
#define IDC_BTN_IN_ONE                  1085
#define IDC_STATIC_SUM_RATIO            1085
#define IDC_STATIC_RATIO                1086
#define IDC_STATIC_ACNT_TARGET          1087
#define IDC_STATIC_ACNT_SOURCE          1088
#define IDC_STATIC_SUBACNT_SOURCE       1089
#define IDC_STATIC_SUBACNT_TARGET       1090
#define IDC_COMBO_FUND                  1091
#define IDC_CHECK_ACNT                  1092
#define IDC_STATIC_ACNT_PWD             1093
#define IDC_STATIC_PRODUCT              1094
#define IDC_SYSTEM_PROP                 1095
#define IDC_SYS_PROP                    1095
#define IDC_STATIC_GRID                 1096
#define IDC_COMBO_TIME                  1097
#define IDC_COMBO_TICK                  1098
#define IDC_STATIC_TIME                 1099
#define IDC_STATIC_SYSTEM               1100
#define IDC_STATIC_STATE                1100
#define IDC_COMBO_SYSTEM                1101
#define IDC_STATIC_TASK                 1101
#define IDC_PROGRESS_CTRL               1102
#define IDC_STATIC_TIME2                1102
#define IDC_STATIC_SYSTEM2              1103
#define IDC_COMBO_STYLE                 1104
#define IDC_STATIC_SET                  1105
#define IDC_BTN_ACNT_MJ                 1106
#define IDC_BTN_FUND_MJ                 1107
#define IDC_STATIC_SISE                 1108
#define IDC_STATIC_STRATEGY             1109
#define IDC_COMBO_STRATEGY              1110
#define IDC_DP_ENT_BEGIN                1111
#define IDC_DP_ENT_END                  1112
#define IDC_DP_LIQ                      1113
#define IDC_EDIT_TS_PL                  1114
#define IDC_EDIT_TS_PERCENT             1115
#define IDC_EDIT_LOSSCUT                1116
#define IDC_COMBO_LOSSCUT_TYPE          1117
#define IDC_STATIC_ACCOUNT              1118
#define IDC_STATIC_SYMBOL               1119
#define IDC_STATIC_PL                   1120
#define IDC_STATIC_ENT_GRID             1121
#define IDC_STATIC_LIQ_GRID             1122
#define IDC_EDIT_PROFIT_TARGET          1123
#define IDC_COMBO_PROFIT_TARGET         1125
#define IDC_STATIC_ARG                  1126
#define IDC_EDIT_ORDER_AMT              1128
#define IDC_STATIC_ENT_CNT_TODAY        1129
#define IDC_STATIC_LAST_ENT_PRICE       1130
#define IDC_CHECK_RUN                   1131
#define ID_FILE_SERVER_MSG              32771
#define ID_FILE_OPEN_SCREEN             32772
#define ID_SETTIME_TO_SERVER            32773
#define ID_ACCOUNT_MANAGE_SUBACCOUNT    32774
#define ID_ACCOUNT_SHOW_DEPOSIT         32775
#define ID_ACCOUNT_MANAGE_PASSWORD      32776
#define ID_ORDER_WINDOW                 32777
#define ID_ORDER_BALANCE                32778
#define ID_ORDER_LIST                   32779
#define ID_ORDER_STOPLIST               32780
#define ID_CHART_WINDOW                 32781
#define ID_CHART_SPREAD                 32782
#define ID_MULTIACCOUNT_MANAGE          32783
#define ID_MULTIACCOUNT_WINDOW          32784
#define ID_MULTIACCOUNT_BRIEF_BALANCE   32785
#define ID_STRATEGY_TOOLBAR             32786
#define ID_DATA_COL                     32787
#define ID_LOGIN_TEST                   32788
#define ID_CHART_ORDER                  32792
#define ID_32793                        32793
#define ID_AUTO_SIGNAL_CONNECT          32794
#define ID_32795                        32795
#define ID_SAVE_CURRENT_SCREEN          32796
#define ID_32797                        32797
#define ID_SET_SYSMONTH                 32798
#define ID_32799                        32799
#define ID_SET_ORDER                    32800
#define ID_32801                        32801
#define ID_ORDER_PANEL                  32802
#define ID_32803                        32803
#define ID_ORDER_TEST                   32804
#define ID_32805                        32805
#define ID_AI                           32806
#define ID_32807                        32807
#define ID_32808                        32808
#define ID_COR_BTWN_PORT                32809
#define ID_COR_BTWN_SIG                 32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        376
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
